export {Inicio} from './Inicio'
export {Comodin} from './Comodin'
export {Nosotros} from './Nosotros'
export {Contactos} from './Contactos'
export { Arquitectura } from './Arquitectura'
export { Ingenieria } from './Ingenieria'